Add docs section about executing coroutines
python-adaptive/adaptive pull request #364
Opened 2022-10-07 09:52 UTC by juandaanieel

Solves #360

2022-10-07 17:16 UTC, basnijholt commented
Awesome @juandaanieel!

I just pushed a small change where I move the imports to the cell where they're used.

2022-10-07 22:58 UTC, basnijholt approved these changes
LGTM! I made a few small changes.

@akhmerov, merge when you're happy with it.

2022-10-07 23:41 UTC, akhmerov commented
Yep! Want to go through the text with @juandaanieel, now it's rather minimal.

2022-10-12 18:19 UTC, akhmerov commented on docs/source/tutorial/tutorial.advanced-topics.md
> +
Please re-add the definition of `f` here: without it, the user won't know the goal and the computation is not fully defined.

2022-10-12 18:21 UTC, akhmerov requested changes

2022-10-12 18:21 UTC, akhmerov commented on docs/source/tutorial/tutorial.advanced-topics.md
> +In this example we will show how to send complex tasks to adaptive as coroutines.
Obsolete comment? Seems to repeat what we now say in the beginning.

2022-10-12 22:56 UTC, basnijholt commented on docs/source/tutorial/tutorial.advanced-topics.md
> +from collections import defaultdict
You do not seem to be using `defaultdict` anywhere.

2022-10-12 22:57 UTC, basnijholt commented on docs/source/tutorial/tutorial.advanced-topics.md
> +learner = adaptive.Learner1D(async_h, bounds=(-3.5, 3.5))
You defined `f_parallel` but use an undefined `async_h`.

2022-10-29 13:56 UTC, akhmerov approved these changes

2022-10-29 13:56 UTC, akhmerov commented
I reworded a couple of sentences. All good to go now, I think. Thanks again @juandaanieel!

2022-10-29 20:05 UTC, merged